## What are Tensors?
Tensors can be anything, every representation of numbers, like scalars, vectors, matrixes and also a multidimensional arrays. Pytorch has a lot of functions and methods that applies on tensors and gives us more functionality to our programms.

## Importing Pytorch

In [ ]:
import torch

## Pytorch Scalars

In [ ]:
# We can create scalar tensors:
t1 = torch.tensor(9)
t2 = torch.tensor(9.99)

# We can see that those are tensors is a scalar using the attribute 'ndim'
print(t1.ndim, t2.ndim)

# Other than 'ndim' we can use the attribute 'shape' (equivelant with 'size()')
print(t1.shape, t2.shape)

# Can also get the data type of a tensor's items
print(t1.dtype, t2.dtype)

# To get the data of a tensor and convert it in a Python class we use 'item()'
print(t1.item(), type(t1.item()))

0 0
torch.Size([]) torch.Size([])
torch.int64 torch.float32
9 <class 'int'>


## Pytorch Higher Dimensions Tensors

In [ ]:
# We can create vectors using:
t1 = torch.tensor([3, 6, 9])

# Printing the shape and the number of dimensions of this tensor:
print(t1.ndim, t1.shape)

# We can create a tensor with specific data type (we can see all data types available in the link above)
t2 = torch.tensor([3, 6, 9], dtype=torch.float32)

print(t2.dtype)

# In the special case that some element of a tensor is a higher data type (like double in a tensor with ints), then all the other
#   elements will became automaticly the higher data type
t3 = torch.tensor([3, 6, 9.])

print(t3.dtype)

# To convert a Tensor to a Python List we use (can also be used for higher dimensions Tensors):
l1 = t1.tolist()

print(l1)

# To get the number of elements in a Tensor we use:
print(t1.numel())

1 torch.Size([3])
torch.float32
torch.float32
[3, 6, 9]
3


In [ ]:
# We can create higher dimesnion tensors:
t1 = torch.tensor([[3, 6, 9], [13, 16, 19]])

# Printing the number of dimension and the shape of the tensor
print(t1.ndim, t1.shape)

# How shape works?
#   First we need to see how many dimensions the tensor has. That will be the length of 'shape' tensor
#   As first element this tensor have the elements (or the subtensors) of the higher dimension, as
#   second element the tensors of the second higher dimension and so on
# We should add that this 'shape' tensor is an iterable

# Another example is:
t2 = torch.tensor([[[3], [6], [9]], [[9], [12], [15]]])

# This tensor has shape: 2x3x1
print(t2.shape)

# If a tensor that we create has invalid (not matching) dimensions then Pytorch raise ValueError
try:
    t3 = torch.tensor([[3], [6, 9]])
except ValueError:
    print("Invalid Dimensions...")

[[3, 6, 9], [13, 16, 19]]
2 torch.Size([2, 3])
torch.Size([2, 3, 1])
Invalid Dimensions...


## Tensor Indexing and Slicing

In [ ]:
# Creating a 1x2x3 tensor
t = torch.tensor([[[3, 6, 9], [6, 9, 12]]])

print(t.shape)

# Indexing works like `numpy` arrays
print(t[0])       # accessing the 2x3 tensor
print(t[0, 0])    # accessing the first vector-tensor
print(t[0, 0, 2]) # accessing the last element of that vector-tensor

# Slicing works also like `numpy` arrays
print(t[0][:, 0])   # accessing the first elements of the 2 vector-tensors
print(t[0][0, 0:2]) # accessing the first 2 elements of the first vector-tensor

# This correlation is due to the fact that Pytorch Tensors are in fact Numpy Arrays that can be run in GPU

torch.Size([1, 2, 3])
tensor([[ 3,  6,  9],
        [ 6,  9, 12]])
tensor([3, 6, 9])
tensor(9)
tensor([3, 6])
tensor([3, 6])


## Convention

In [ ]:
# Typically we write the identifiers of scalar and vector Tensors with lowercase names and the higher
#   dimension Tensors with upeprcase

t1 = torch.tensor(9.)
t2 = torch.tensor([3, 6, 9])
T1 = torch.tensor([[3, 6], [6, 9]])
T2 = torch.tensor([[[3], [6]], [[9], [12]], [[15], [18]]]) # 3x2x1 Tensor

## Changing Data Type of a Tensor

In [ ]:
t1 = torch.tensor([3, 6, 9], dtype=torch.int16)

print(t1, t1.dtype)

# We can change that data type of a Tensor using (don't share memory locations):
t2 = t1.type(torch.float32)

print(t2, t2.dtype)

tensor([3, 6, 9], dtype=torch.int16) torch.int16
tensor([9., 6., 9.]) torch.float32


## Random Tensors

In [ ]:
# Learning to create Tensors with `random` numbers is essential in ML algorithms because at the beginning of learning
#   we should initialize the weights (the rule finders) with random numbers and through the features and labels we will
#   correct those random numbers in the appropriate rules.

# Create a random Tensor, according to the uniform distribution [0, 1)
t1 = torch.rand(1, 3, 4)  # As argument we pass the shape

print(t1.shape, t1)

# The 'shape' of the Tensor can be passed using 'size=(...)'
t2 = torch.rand(size=(1, 3, 4))

print(t2.shape, t2)

# So for example if we have an RGB image of 244x235 bits we can create the weight Tensor as follows:
t3 = torch.rand(size=(3, 244, 235)) # Where 3: number of channels, 244: height, 235: width

print(t3.shape)


# To create a random Tensor based on the standard Distribution (mean=0, variance=1) we use:
t4 = torch.randn(size=(3, 3))

print(t4)


# To create a random Tensor that contains random intagers from n1 (default 0) to n2 we use [n1, n2):
t4 = torch.randint(3, 9, size=(2, 2))

print(t4)


# To create a random vector-tensor with all intagers for 0 to n-1 we use:
t5 = torch.randperm(9)

print(t5)


# We can also set manual the seed:
gen = torch.Generator()
gen.manual_seed(36912151821)

t5 = torch.rand(size=(9,), generator=gen)

print(t5)

torch.Size([1, 3, 4]) tensor([[[0.2677, 0.8256, 0.2678, 0.5786],
         [0.9565, 0.2914, 0.1297, 0.1660],
         [0.6565, 0.2139, 0.5560, 0.3178]]])
torch.Size([1, 3, 4]) tensor([[[0.5156, 0.0890, 0.2774, 0.6858],
         [0.4877, 0.4849, 0.2816, 0.2211],
         [0.5426, 0.3132, 0.7145, 0.1043]]])
torch.Size([3, 244, 235])
tensor([[ 2.3907, -2.0185,  0.2982],
        [ 2.5956, -1.6334, -0.9039],
        [-0.9368,  0.3874,  0.8656]])
tensor([[4, 8],
        [8, 5]])
tensor([5, 0, 7, 1, 6, 2, 8, 3, 4])
tensor([0.6036, 0.0122, 0.5503, 0.7819, 0.5431, 0.2678, 0.8170, 0.7145, 0.5579])


## Empty-Ones-Zeros Tensors

In [ ]:
# The default data type of those Tensors is 'float32'

# Creating an empty-tensor
t1 = torch.empty(9)
t2 = torch.empty(size=(2, 2))

print(t2.shape, t2)


# Creating ones-tensor
t3 = torch.ones(3)
t4 = torch.ones(size=(1, 3))

print(t4)


# Creating zeros-tensor
t5 = torch.zeros(3)
t6 = torch.zeros(size=(1, 3))

print(t6)

torch.Size([2, 2]) tensor([[-1.2252e-34,  4.5860e-41],
        [-1.2252e-34,  4.5860e-41]])
tensor([[1., 1., 1.]])
tensor([[0., 0., 0.]])


## Eye-Full Tensors

In [ ]:
# To create the identical Matrix nxn we use:
t1 = torch.eye(9)

print(t1.shape, t1)

# To create a Tensor of custom dimensions with the same element:
t2 = torch.full(size=(2, 2), fill_value=3)
print(t2)

torch.Size([9, 9]) tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1.]])
tensor([[3, 3],
        [3, 3]])


## Range Tensors

In [ ]:
# To create the range [n1, n2) we use (default n1=0):
t1 = torch.arange(3, 10)
t2 = torch.arange(start=1, end=10, step=2) # With step

print(t1, t2)

# To create a range Tensor [n1, n2) with n3 elements we use:
t3 = torch.linspace(start=-1, end=1, steps=10)

print(t3)

tensor([3, 4, 5, 6, 7, 8, 9]) tensor([1, 3, 5, 7, 9])
tensor([-1.0000, -0.7778, -0.5556, -0.3333, -0.1111,  0.1111,  0.3333,  0.5556,
         0.7778,  1.0000])


## Like Tensors

In [ ]:
# We can create a Tensor base on the shape of another Tensor
t1 = torch.rand(size=(3, 3))
t2 = torch.ones(size=(9,))

t3 = torch.zeros_like(input=t2)
t4 = torch.randn_like(input=t1)

print(t3.shape, t3)
print(t4.shape, t4)

torch.Size([9]) tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([3, 3]) tensor([[ 0.6418,  0.8502,  0.8367],
        [-0.7127, -1.4369, -0.5261],
        [-1.0469, -1.0671,  0.9048]])


## Copying Tensors

In [ ]:
t1 = torch.tensor([[3, 6, 9], [12, 15, 18]])

# We can deep-copy a Tensor using:
t2 = t1.detach().clone()

print(t1, t2)

t2[1][0] = torch.tensor(9)

print(t1, t2)

tensor([[ 3,  6,  9],
        [12, 15, 18]]) tensor([[ 3,  6,  9],
        [12, 15, 18]])
tensor([[ 3,  6,  9],
        [12, 15, 18]]) tensor([[ 3,  6,  9],
        [ 9, 15, 18]])



## Reshaping Tensors

In [ ]:
t = torch.tensor([[3, 6, 9], [12, 15, 18]])

# We can get the Transpose Tensor using:
print(t.T)

# We can reshape the tensor, but the new dimension must be compatable with the original (the reshaped Tensor is a shallow copy of original)
print(t.reshape(1, 3, 2))
print(t.reshape(6))
# Similar we can do:
print(t.view(1, 3, 2))
print(t.view(6))

# The issue with shallow copy
a = t.reshape(6)
a[0] = 9
print(t)
a = torch.tensor([3])
print(t)

# We can convert a Tensor into a vector-tensor (returns a view):
print(t.flatten())

# If we want Pytorch to handle the exact dimensions that need to be passed so the new Tensor to be compatable with the original:
print(t.reshape(3, -1))
print(t.reshape(-1))

tensor([[ 3, 12],
        [ 6, 15],
        [ 9, 18]])
tensor([[[ 3,  6],
         [ 9, 12],
         [15, 18]]])
tensor([ 3,  6,  9, 12, 15, 18])
tensor([[[ 3,  6],
         [ 9, 12],
         [15, 18]]])
tensor([ 3,  6,  9, 12, 15, 18])
tensor([[ 9,  6,  9],
        [12, 15, 18]])
tensor([[ 9,  6,  9],
        [12, 15, 18]])
tensor([ 9,  6,  9, 12, 15, 18])
tensor([[ 9,  6],
        [ 9, 12],
        [15, 18]])
tensor([ 9,  6,  9, 12, 15, 18])


## Stacking Tensors

In [ ]:
t = torch.tensor([[3, 6], [9, 12]])

# To vertically stack 2 or more Tensors we do:
print(torch.stack((t, t, t), dim=0)) # works like t = [t, t, t]: ndim = 3
print(torch.vstack((t, t, t)))       # The same but reducing the ndim to 2

# To horizontally stacj 2 or more Tensors we do:
print(torch.stack((t, t, t), dim=1)) # works like t = [[t[0], t[0], t[0]], [t[1], t[1], t[1]]]
print(torch.hstack((t, t, t)))       # The same but reducing the ndim to 2

# Another stacking method is to stack element-wise
print(torch.dstack((t, t, t)))

tensor([[[ 3,  6],
         [ 9, 12]],

        [[ 3,  6],
         [ 9, 12]],

        [[ 3,  6],
         [ 9, 12]]])
tensor([[ 3,  6],
        [ 9, 12],
        [ 3,  6],
        [ 9, 12],
        [ 3,  6],
        [ 9, 12]])
tensor([[[ 3,  6],
         [ 3,  6],
         [ 3,  6]],

        [[ 9, 12],
         [ 9, 12],
         [ 9, 12]]])
tensor([[ 3,  6,  3,  6,  3,  6],
        [ 9, 12,  9, 12,  9, 12]])
tensor([[[ 3,  3,  3],
         [ 6,  6,  6]],

        [[ 9,  9,  9],
         [12, 12, 12]]])


## Squeeze and Unsqueeze Tensors

In [ ]:
# We can remove and add 1 dimensions to our Tensors
t = torch.tensor([[3, 6, 9]])

print(t, t.shape)

t = t.reshape((3))

print(t.squeeze())        # Remove all the single dimensions (1d)
print(t.unsqueeze(dim=1)) # Add one dimension alongside axis 1
print(t.unsqueeze(dim=0)) # Add one dimension alongside axis 0

tensor([[3, 6, 9]]) torch.Size([1, 3])
tensor([3, 6, 9])
tensor([[3],
        [6],
        [9]])
tensor([[3, 6, 9]])


## Permute the Dimensions of a Tensor

In [ ]:
t = torch.tensor([[[3, 6], [6, 9], [9, 12]]]) # shape 1x3x2

# We can rearange the dimensions of a Tensor using (returns a view):
print(t.permute(2, 1, 0)) # shape: 2x3x1
print(t.permute(1, 2, 0)) # shape: 3x2x1
print(t.permute(0, 2, 1)) # shape: 1x2x3

tensor([[[ 3],
         [ 6],
         [ 9]],

        [[ 6],
         [ 9],
         [12]]])
tensor([[[ 3],
         [ 6]],

        [[ 6],
         [ 9]],

        [[ 9],
         [12]]])
tensor([[[ 3,  6,  9],
         [ 6,  9, 12]]])


## Mathematical Operations with Tensors.

In [ ]:
t1 = torch.tensor([3, 6, 9])
t2 = torch.tensor([9, 6, 3])

# The operations between Tensors and scalars are element-wise operation (work with all operators):
print(t1 + 3)
print(t1 * 3)

# All those methods can be called from a Tensor, by adding the suffix '_' and then passing the appropriate arguments

# For performing operations between 2 Tensors we use:
print(torch.add(t1, t2))         # + element-wise
print(torch.sub(t1, t2))         # - element-wise
print(torch.mul(t1, t2))         # * element-wise
print(torch.div(t1, t2))         # / element-wise
print(torch.fmod(t1, t2))        # % element-wise
print(torch.dot(t1, t2))         # dot-product of 2 vector-tensors
print(torch.matmul(t1, t2))      # @, mm the dot-product of 2 tensors

print(torch.sqrt(t1))            # square root
print(torch.abs(t1))             # |t|
print(torch.neg(t1))             # -t
print(torch.ceil(t1))            # ceil
print(torch.floor(t1))           # floor

print(torch.pow(t1, exponent=2)) # ** exponent
print(torch.sum(t1))             # Σ
print(torch.nansum(t1))          # Σ with nan = 0
print(torch.prod(t1))            # Π

tensor([ 6,  9, 12])
tensor([ 9, 18, 27])
tensor([12, 12, 12])
tensor([-6,  0,  6])
tensor([27, 36, 27])
tensor([0.3333, 1.0000, 3.0000])
tensor([3, 0, 0])
tensor(90)
tensor(90)
tensor([1.7321, 2.4495, 3.0000])
tensor([3, 6, 9])
tensor([-3, -6, -9])
tensor([3, 6, 9])
tensor([3, 6, 9])
tensor([ 9, 36, 81])
tensor(18)
tensor(18)
tensor(162)


## Mathematical Functions to Tensors

In [ ]:
t = torch.tensor([3, 6, 9])

# Trigonometric Functions
print(torch.cos(t))
print(torch.sin(t))
print(torch.tan(t))
print(torch.cosh(t))
print(torch.sinh(t))
print(torch.tanh(t))
# Converting degrees to rads
print(torch.deg2rad(torch.tensor([0, 90, 180, 270, 360], dtype=torch.float32)))
print(torch.rad2deg(torch.tensor([0, torch.pi/2, torch.pi, 3*torch.pi/2, 2*torch.pi], dtype=torch.float32)))

# Exponential and Logarithic Functions
print(torch.exp(t))   # e ^ t
print(torch.exp2(t))  # 2 ^ t
print(torch.log(t))   # ln(t)
print(torch.log2(t))
print(torch.log10(t))

# The sigmoid Function
print(torch.sigmoid(t))

# Probability Functions: need floating point numbers
t = t.type(torch.float32)
print(torch.mean(t))
print(torch.median(t))   # The miidle value in the sorted Tensor t
print(torch.std(t))      # Standard Deviation (σ) of elements from mean
print(torch.var(t))      # Variance (σ^2) of elements from mean
print(torch.std_mean(t)) # The tuple that contains std and mean
print(torch.var_mean(t)) # The tuple that contains var and mean

# Pytorch also support Fourier Transformations

tensor([-0.9900,  0.9602, -0.9111])
tensor([ 0.1411, -0.2794,  0.4121])
tensor([-0.1425, -0.2910, -0.4523])
tensor([  10.0677,  201.7156, 4051.5420])
tensor([  10.0179,  201.7132, 4051.5420])
tensor([0.9951, 1.0000, 1.0000])
tensor([0.0000, 1.5708, 3.1416, 4.7124, 6.2832])
tensor([  0.,  90., 180., 270., 360.])
tensor([  20.0855,  403.4288, 8103.0840])
tensor([  8.,  64., 512.])
tensor([1.0986, 1.7918, 2.1972])
tensor([1.5850, 2.5850, 3.1699])
tensor([0.4771, 0.7782, 0.9542])
tensor([0.9526, 0.9975, 0.9999])
tensor(6.)
tensor(6.)
tensor(3.)
tensor(9.)
(tensor(3.), tensor(6.))
(tensor(9.), tensor(6.))


## Other Functions

In [ ]:
t = torch.tensor([[9, 6, 3], [15, 18, 12]])
t1 = torch.tensor([float("inf"), 9, 3])
t2 = torch.tensor([3, 9, float("nan")])

# Minimum and Maximum values of a Tensor
print(torch.max(t))    # converting the Tensor into a vector-tensor
print(torch.argmax(t)) # the index of the maximum in the vector-tensor
print(torch.min(t))
print(torch.argmin(t))

# Returning how many non zero element exists in the Tensor
print(torch.count_nonzero(t))

# Return boolean-tensor
print(torch.isinf(t1))
print(torch.isnan(t2))

# Return the correct indexes of each element on the sorted version of Tensor
print(torch.argsort(t))

# Sorting a Tensor
sorted_t, indexes = torch.sort(input=t, dim=1, descending=True) # dim=1 for sorting each row and dim=0 for sorting each column
print(sorted_t, indexes)                                        # descending=True for descending sorting

tensor(18)
tensor(4)
tensor(3)
tensor(2)
tensor(6)
tensor([ True, False, False])
tensor([False, False,  True])
tensor([[2, 1, 0],
        [2, 0, 1]])
tensor([[ 9,  6,  3],
        [18, 15, 12]]) tensor([[0, 1, 2],
        [1, 0, 2]])


## Conditional Operators

In [ ]:
t1 = torch.tensor([3, 6, 9])
t2 = torch.tensor([3, 9, 9])

print(t1 == t2) # torch.eq(t1, t2)
print(t1 != t2) # torch.ne(t1, t2)
print(t1 > t2)  # torch.lt(t1, t2)

# We have available by Pytorch all the other operators

tensor([ True, False,  True])
tensor([False,  True, False])
tensor([False, False, False])


## Interoperability with Numpy.

In [ ]:
# The difference of Pytorch's Tesnors and Numpy's Arrays is that the last only works on cpu.

import numpy as np
import torch

a = np.array([3, 6, 9])
t = torch.tensor([3, 6, 9])

t1 = torch.as_tensor(a, dtype=torch.float32) # Converting an object to Tensor (don't share memory)
t2 = torch.from_numpy(a)                     # Converting a numpy array into a Tensor (takes not any other arg) (share memory)
t3 = torch.from_numpy(a).type(torch.int16)   # Converting a numpy array into a Tensot and changing the data type (don't share memory)
a1 = t.numpy()                               # Converting a Tensor into a numpy array (share memory)

print(t1, type(t1))
print(t2, type(t2))
print(t3, type(t3))
print(a1, type(a1))

tensor([3., 6., 9.]) <class 'torch.Tensor'>
tensor([3, 6, 9]) <class 'torch.Tensor'>
tensor([3, 6, 9], dtype=torch.int16) <class 'torch.Tensor'>
[3 6 9] <class 'numpy.ndarray'>


## Tensor Devices

In [ ]:
# We can make numerical computations between Tensors either on CPU or GPU
# The attribute that shows us where a Tensor is allocated is 'device' or 'get_device()'

t1 = torch.tensor([3, 6, 9]) # default device 'cpu'

print(t1.device)

# We can set the device when initializing the Tensor object
t2 = torch.tensor([3, 6, 9], device="cpu") # the same as 'device=None'

print(t2.device)

# To enable GPU on Google Colab: Runtime->Change runtime type

t3 = torch.tensor([3, 6, 9], device="cuda") # cuda for GPU

print(t3.device)

# Can also change the device after initialization
d = torch.device("cuda") # device object

# Checking if GPU is available ('to()' returns a copy of the Tensor into that device, doesn't move the Tesnor into the device, unlike 'nn.Module')
if torch.cuda.is_available():
    t1 = t1.to(d)

print(t1.device)

# If we had more than 1 GPU we can count them:
print(torch.cuda.device_count())

cpu
cpu
cuda:0
cpu
1


## Device Agnostic Code

In [ ]:
# In all out Pytorch files we are going to use this line:

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

# Simply set the device into cuda if GPU is available

cpu


## Working with Gradients.


In [ ]:
# Another powerfull feature of Pytorch is that it calculate gradients very eazy.

# To calculate the gradients we need to add the requires_grad=True parameter on each tensor that is inlcuded in the function.

x = torch.tensor(9., requires_grad=True)
y = torch.tensor(2., requires_grad=True)
z = torch.tensor(4., requires_grad=True)

f = x**2 + y*x + z  # The function that we want to calculate the gradient.

f.backward()        # This method compute all the gradients automatically with respect of x and y and z
                    #   Those gradients are stored in the 'grad' attribute of each Tensor.

g1 = x.grad         # 20 because the derivative of f with respect of x is 'f = 2x + y'.
g2 = y.grad         # 9 because the derivative of f with respect of y is 'f = x'.
g3 = z.grad         # 1 because the derivative of f with respect of z is 'f = 1'.

print(g1, g2, g3)

# Reseating the gradients to zero (Nessesary at the end of each epoch)
g1.zero_()
g2.zero_()
g3.zero_()

print(g1, g2, g3)

# If we dont work with gradients (makes thinks faster).
with torch.no_grad():
    pass

tensor(20.) tensor(9.) tensor(1.)
tensor(0.) tensor(0.) tensor(0.)
